### ISSUE TITLE
nw:load-graphml creates non-directed links

### ISSUE THREAD

**Issue by arthurhjorth** [NetLogo/NW-Extension#129]
When importing a network with `nw:load-graphml` links report `false` to both `is-directed-link?` and `is-undirected-link?`.

This happens with and without code that implies direction of links. I tested by having create-link-with and create-link-to in the code. As usual, you get runtime error if you have something that implies both directed and undirected, so at least it doesn't break that.

**Comment by birbilis** [comment]
...or if you had breed inheritance
