### ISSUE TITLE
nw:save-graphml file name 

### ISSUE THREAD

**Issue by deryc** [NetLogo/NW-Extension#148]
I can't seem to add a random number to my file name with using nw:save-graphml

I've been trying:

nw:save-graphml "test" random 70000 ".graphml"

any help would be much appreciated.

**Comment by nicolaspayette** [comment]
Hi! Thanks for your report, but this is not a NW extension problem. Just use the [`word`](http://ccl.northwestern.edu/netlogo/docs/dictionary.html#word) primitive to construct your filename:

    nw:save-graphml (word "test" random 70000 ".graphml")
