### ISSUE TITLE
Adjacency matrix order

### ISSUE THREAD

**Issue by ThomasCNotts** [NetLogo/NW-Extension#152]
If I run:

    nw:save-matrix "GraphName.csv"

will the nodes be in turtle number order? Will the first row/column in the adjacency matrix ouput be Turtle 0?

If they are, how do I then output the values of a turtle-own variable in turtle number order? Does file-write output in turtle number order?

Thank you,

Thomas

**Comment by qiemem** [comment]
This is indeed a duplicate.
