### ISSUE TITLE
how to use nw-extension features in netlogo

### ISSUE THREAD

**Issue by bkashif** [NetLogo/NW-Extension#161]
I am new to this NW-Extension. Someone plz tell how to use the following command in netlogo directly as i need to generate a preferential attachment model. 
nw:generate-preferential-attachment turtles links 100 [ set color red ]
Thanks

**Comment by bkashif** [comment]
ERROR: Nothing named NW:GENERATE-PREFERENTIAL-ATTACHMENT has been defined

**Comment by qiemem** [comment]
That command should work as you've written. Did you include `extensions [ nw ]` at the top of your code? What's going wrong?
