### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/NW-Extension#162]
"...so the result if reported as a list of agentsets, in random order."

should be

"...so the result is reported as a list of agentsets, in random order."

in http://ccl.northwestern.edu/netlogo/docs/nw.html

**Comment by qiemem** [comment]
Thanks! Fixed by 592d2c0f410ce4774ba155d383854ff1980961fd. Should appear in the main NetLogo docs in the next release.
