### ISSUE TITLE
WeightedPathTo is supposed to return NumberType | BooleanType

### ISSUE THREAD

**Issue by JZschache** [NetLogo/NW-Extension#163]
I came across a small bug: NetLogo expects `nw:weighted-path-to` to return a number or a boolean instead of a list: https://github.com/NetLogo/NW-Extension/blob/master/src/main/org/nlogo/extensions/nw/prim/Paths.scala#L110

This impedes the usage of `map [?]  (nw:weighted-path-to myself  "x")`

Thank your for the nw-extension!

**Comment by nicolaspayette** [comment]
Thanks for catching this, @JZschache ! It should be fixed in the forthcoming NetLogo release.
