### ISSUE TITLE
NW does not work in applet

### ISSUE THREAD

**Issue by frank0065** [NetLogo/NW-Extension#167]
I wrote a simple netlogo test code with only one nw function (nw:path-to) and saved it as an applet. The applet can be properly loaded on my browser, but gets stuck just before the nw-path function. I replaced the two NetLogoLite files with the new ones compiled from the source code of NetLogo 5.3.1 with the lite.txt file replaced according to "Producing an alternate NetLogoLite.jar" (https://github.com/NetLogo/NW-Extension/wiki/Producing-an-alternate-NetLogoLite.jar).
Anyone can help?

**Comment by qiemem** [comment]
Unfortunately, applets have been officially deprecated in NetLogo. As such, the NW extension no longer supports applets. Sorry about that!

You can read more about the decision to deprecate applets here: https://github.com/NetLogo/NetLogo/wiki/Applets
