### ISSUE TITLE
How do I access the vertices an undirected-link-breed?

### ISSUE THREAD

**Issue by akashrajkn** [NetLogo/NW-Extension#186]
Hi, I am using the network extension to find the shortest path between two links (`nw:path-to`),
```
extensions [nw]

breed [agents agent]
undirected-link-breed [paths path]

ask agent 3 [set alpha nw:path-to agent 10]
```
This code returns `[(path 3 4) (path 4 10)]` . How do I access the breed-ids: 3, 4, 10? Ideally I want to access it like this `get_path (path 3 4)"` which returns something like [3 4].

Cheers. And thank you for the software.

**Comment by nicolaspayette** [comment]
I think that what you are looking for is either [`both-ends`](http://ccl.northwestern.edu/netlogo/docs/dictionary.html#both-ends) or [`nw:turtles-on-path-to`](http://ccl.northwestern.edu/netlogo/docs/nw.html#nw:turtles-on-path-to).

That being said, GitHub issues are not really the right place to ask that kind of questions (they should mainly be used for reporting bugs). Next time (or if you have further questions), I would suggest posting a question to https://stackoverflow.com/questions/ask.
