### ISSUE TITLE
`save-matrix` should omit space at the end of output line

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/NW-Extension#196]
The current code outputs something like:

```
0.00_1.00_0.00_
0.00_0.00_0.00_
0.00_0.00_1.00_
```

where `_` stands for a space. The trailing space at the end of each line is unnecessary and can trip delimited-file reading functions.

The offending line is:

https://github.com/NetLogo/NW-Extension/blob/hexy/src/main/org/nlogo/extensions/nw/jung/io/Matrix.scala#L34

It's an easy fix and I'd be happy to provide a PR if welcome.

**Comment by LaCuneta** [comment]
If you have time to provide a fix, I'm happy to review + merge
