### ISSUE TITLE
Error while running in Headless mode

### ISSUE THREAD

**Issue by egonzales2000** [NetLogo/NW-Extension#201]
Hi, 

I'm running NetLogo on a cluster and run into the following error:

> Exception in thread "main" java.lang.ExceptionInInitializerError
> 	at org.openide.util.lookup.implspi.ActiveQueue.queue(ActiveQueue.java:70)
> 	at org.openide.util.lookup.AbstractLookup.activeQueue(AbstractLookup.java:753)
> 	at org.openide.util.lookup.AbstractLookup.access$600(AbstractLookup.java:80)
> 	at org.openide.util.lookup.AbstractLookup$ReferenceToResult.<init>(AbstractLookup.java:1351)
> 	at org.openide.util.lookup.AbstractLookup$ReferenceToResult.<init>(AbstractLookup.java:1334)
> 	at org.openide.util.lookup.AbstractLookup.lookup(AbstractLookup.java:490)
> 	at org.openide.util.lookup.ProxyLookup$R.initResults(ProxyLookup.java:391)
> 	at org.openide.util.lookup.ProxyLookup$R.myBeforeLookup(ProxyLookup.java:655)
> 	at org.openide.util.lookup.ProxyLookup$R.computeResult(ProxyLookup.java:550)
> 	at org.openide.util.lookup.ProxyLookup$R.allInstances(ProxyLookup.java:510)
> 	at org.openide.util.lookup.ProxyLookup$R.allInstances(ProxyLookup.java:506)
> 	at org.nlogo.extensions.nw.gephi.GephiUtils$.$anonfun$shutdownStupidExtraThreads$1(GephiUtils.scala:33)
> 	at org.nlogo.extensions.nw.gephi.GephiUtils$.withClassLoaderContext(GephiUtils.scala:16)
> 	at org.nlogo.extensions.nw.gephi.GephiUtils$.$anonfun$withNWLoaderContext$1(GephiUtils.scala:10)
> 	at org.nlogo.extensions.nw.gephi.GephiUtils$.shutdownStupidExtraThreads(GephiUtils.scala:33)
> 	at org.nlogo.extensions.nw.NetworkExtension.unload(NetworkExtension.scala:41)
> 	at org.nlogo.workspace.ExtensionManager$JarContainer.unload(ExtensionManager.scala:97)
> 	at org.nlogo.workspace.ExtensionManager.$anonfun$reset$1(ExtensionManager.scala:293)
> 	at org.nlogo.workspace.ExtensionManager.$anonfun$reset$1$adapted(ExtensionManager.scala:292)
> 	at scala.collection.Iterator.foreach(Iterator.scala:929)
> 	at scala.collection.Iterator.foreach$(Iterator.scala:929)
> 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
> 	at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:210)
> 	at org.nlogo.workspace.ExtensionManager.reset(ExtensionManager.scala:292)
> 	at org.nlogo.workspace.AbstractWorkspace.dispose(AbstractWorkspace.java:85)
> 	at org.nlogo.workspace.AbstractWorkspaceScala.org$nlogo$workspace$Components$$super$dispose(AbstractWorkspaceScala.scala:24)
> 	at org.nlogo.workspace.Components.dispose(Components.scala:59)
> 	at org.nlogo.workspace.Components.dispose$(Components.scala:58)
> 	at org.nlogo.workspace.AbstractWorkspaceScala.dispose(AbstractWorkspaceScala.scala:24)
> 	at org.nlogo.headless.Main$.runExperiment(Main.scala:25)
> 	at org.nlogo.headless.Main$.$anonfun$main$1(Main.scala:12)
> 	at org.nlogo.headless.Main$.$anonfun$main$1$adapted(Main.scala:12)
> 	at scala.Option.foreach(Option.scala:257)
> 	at org.nlogo.headless.Main$.main(Main.scala:12)
> 	at org.nlogo.headless.Main.main(Main.scala)
> Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.ref.ReferenceQueue$Lock java.lang.ref.ReferenceQueue.lock accessible: module java.base does not "opens java.lang.ref" to unnamed module @14e2e1c3
> 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
> 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
> 	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
> 	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
> 	at org.openide.util.lookup.implspi.ActiveQueue$Impl.<clinit>(ActiveQueue.java:83)
> 	... 35 more
> 

I tried different Netlogo versions (everything since 6.0) and also different different jdks. Anybody an idea how to solve this?

**Comment by LaCuneta** [comment]
@egonzales2000 Which Java version are you running NetLogo with?  That looks like it might be caused by running NetLogo with a version greater than Java 8 (the only version NetLogo 6.2.2 supports).

**Comment by egonzales2000** [comment]
Hi, thanks so much. With jdk 8 everything works as expected. Just wasted 2 days for that (Did not think much on further testing jdks as Netlogo runs perfectly with e.g. jdk 16, it's just the nw extension which make problems and I thought this is related to #194)

**Comment by LaCuneta** [comment]
@egonzales2000 Oof, sorry to hear about your wasted time, but I'm glad you got it resolved.
