### ISSUE TITLE
Should egeinvector centrality work on subcomponents for disconnected networks?

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/NW-Extension#44]
Egeinvector centrality is theoretically not defined for for disconnect networks. It could, however, calculate it separately for each subcomponents.

This is how `closeness centrality` already work, and it would make sense to do the same for egeinvector, it seems.

Would be worth seeing what other package do with that (or ask experts).

(By the way, Jung lets you call it on disconnected networks and just gives you nonsensical results.)

**Comment by qiemem** [comment]
Yes, and now it does. See #168
