### ISSUE TITLE
weighted-link-distance takes weight variable name as a string

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/NW-Extension#5]
When calculating a weighted distance, the user needs to be able to specify a link variable to use as the weight. Currently, this is done by passing the name of the variable as a string. This works well but seems less than ideal because:

* it deviates from standard NetLogo syntax
* the compiler cannot check that the variable actually exists
* we could conceivably want to specify a composite weight (e.g. "a * b")

The reason I did it that way is that I want the results to be cached, and I need to know if we are using the *same* weight variable. Ideally, the user would be able to pass a reporter task, but I don’t know how to do that using reporter tasks, or even if it is possible.

If not possible, it leaves us with the alternatives of either keeping that way, or give up on the caching.

**Comment by qiemem** [comment]
Fixed in 94afd4341bec3864f9777e0028c179a24e1c87c2
